# Generated by Django 4.2.1 on 2023-06-08 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
        ),
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('repeat', models.BooleanField()),
                ('description', models.CharField(max_length=1000)),
                ('initial_time', models.DateField()),
                ('end_time', models.DateField()),
                ('repeat_until', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scheduler.user')),
            ],
            bases=('scheduler.user',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scheduler.user')),
                ('register', models.IntegerField(verbose_name='Register')),
            ],
            bases=('scheduler.user',),
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_computers', models.IntegerField(verbose_name='Number of Computers')),
                ('has_blackboard', models.BooleanField(verbose_name='True if it has blackboard')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler.department')),
            ],
        ),
    ]
