# Generated by Django 4.2.1 on 2023-06-08 19:56

from django.db import migrations

def create_data(apps,schema_editor):
    Teacher = apps.get_model('scheduler', 'Teacher')
    Admin = apps.get_model('scheduler', 'Admin')
    Department = apps.get_model('scheduler','Department')

    Teacher(name="Joao Mili", email="joaoMili@meu_email.com", password="teste123", register="202301").save()
    Teacher(name="Cris Scarpatdesa", email="cris@meu_email.com", password="teste987", register="202302").save()

    Admin(name="Hiuri Carriço", email="hiuri@meu_email.com", password="admin").save()

    Department(name="Informática", code="INF").save()

class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_department_code'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
