# Generated by Django 4.2.1 on 2023-06-10 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_scheduler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduling',
            old_name='initial_time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='department',
            name='closing_time',
            field=models.TimeField(null=True, verbose_name='Closing Time'),
        ),
        migrations.AddField(
            model_name='department',
            name='opening_time',
            field=models.TimeField(null=True, verbose_name='Opening Time'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='code',
            field=models.CharField(default='', max_length=20, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='scheduling',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scheduler.teacher'),
        ),
        migrations.AddField(
            model_name='scheduling',
            name='laboratory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scheduler.laboratory'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(default='', max_length=10, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='repeat',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='repeat_until',
            field=models.DateField(null=True),
        ),
    ]
