# Generated by Django 4.2.1 on 2023-06-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_user_is_active_user_is_staff_user_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
